#!/bin/bash

# Archway: an easy way for installing Arch Linux/Manjaro and Debian/Ubuntu
# Licensed under the MIT License.

# Script declaration
SCRIPTNAME="${0##*[\\/]}"
SCRIPTVER="2020.3.5"
black="\u001b[30m"
red="\u001b[31m"
green="\u001b[32m"
yellow="\u001b[33m"
blue="\u001b[34m"
magenta="\u001b[35m"
cyan="\u001b[36m"
white="\u001b[37m"
nc="\u001b[0m"


function pause() {
    prompt="$1"
    echo -e -n "\033[1;36m$prompt"
    echo -e -n '\033[0m'
    read
}

function archway() {
  if [[ -f archwayrc ]]; then
  . archwayrc
else
  echo "[!!] archwayrc not found! Check if it exists, and make sure to edit it with your preferences."
  exit 127
fi

echo "[archway] by bashelled"
echo "The following will be partitioned and formatted:"
echo " -> Root: $root"
echo " -> Boot: $boot"
echo " -> Home: $home"
echo " -> Swap: $swap"
echo " -> Your user will be called $user and be given the password '$passwd'"
echo " -> User root will get the password '$rootpwd'"
echo " -> Your hostname will be called $host"
echo " -> The desktop will be $deskenv"
echo " -> The default keymap will be $vcons"
echo " -> The following will be installed to the new system: $pacstrap"
echo " -> The timezone will be set to $timezone and the locale will be $locale"
echo " --> Use Ctrl-C to exit, and Enter to continue"
echo " ==> P.S. Edit the archwayrc file to customize your install"
echo " ==> [!!] Make sure it exists, and has your preferences in it!"
pause "[Are you sure you want to proceed?] "
pause "[Are you really sure you want to proceed?] "
clear

if [[ -d /sys/firmware/uefi ]]; then
  uefion=1
fi
echo "===> Installing Arch..."
sleep 1
echo "Set keymap"
if loadkeys $vcons; then
  echo "$vcons keymap loaded!"
else
  echo "There was a problem loading the $vcons keymap."
  exit 127
fi

echo "Format partitions"
mkfs.ext4 /dev/$root
if [[ "$uefion" == "1" ]]; then
  mkfs.fat -F 32 /dev/$boot
else
  mkfs.ext4 /dev/$boot
fi
mount /dev/$root /mnt
mkdir -p /mnt/{boot,home}
mount /dev/$boot /mnt/boot
mount /dev/$home /mnt/home

echo "Installing..."
if pacstrap /mnt $pacstrap && genfstab -U /mnt >> /mnt/etc/fstab; then
  echo "Pacstrapped packages!"
else
  echo "Fatal problem with Pacstrap."
fi

if arch-chroot /mnt ln -sf /usr/share/zoneinfo/$timezone /etc/localtime && \
echo $locale > /etc/locale.gen && \
locale-gen && \
echo LANG=$locale > /etc/locale.conf && \
echo KEYMAP=$vcons > /etc/vconsole && \
echo $host > /etc/hostname && \
echo "127.0.0.1	localhost" > /etc/hosts && \
echo "::1		localhost" >> /etc/hosts && \
echo "127.0.1.1	$host.localdomain	$host" >> /etc/hosts && \
(echo $rootpwd; echo $rootpwd) | passwd root && \
useradd $user -m -r -p $passwd && \
mkinitcpio -P && \
bootctl install && bootctl update; then
  echo "Done! Reboot into your system."
else
  echo "Failure."
}

function usage()
{
        cat << EOF
archway version $SCRIPTVER
Archway is an easy to use Arch Linux installer written
entirely in shell that allows you to tweak to your
preferences, one by one.

Usage: $SCRIPTNAME [-*] [options] command

  -h, --help              display this help and exit
  -V, --version           output version information and exit
EOF
}

function version() {
echo "[archway] by bashelled"
echo "version $SCRIPTVER"
echo "Copyright (c) 2021-present Bashel"
}

if [[ "$1" == "-h" || "$1" == "--help" ]]; then
        usage
elif [[ "$1" == "-V" || "$1" == "--version" ]]; then
        version
else
        archway
fi
